### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by joelnb** [pengutronix/monitoring-check-systemd-service#1]
Thanks for the useful tool!

I was wondering if you would consider adding a license of some sort so that people know if they are able to use this in their environment? I haven't prepared a pull request because I'm unsure what license you would choose but I would be happy to do so if you let me know.

**Comment by Farom** [comment]
You are totally right. I'll fix that soon.

**Comment by Farom** [comment]
0-BSD Licence added.

**Comment by joelnb** [comment]
Thanks for that & good choice on the license.
